puts "Hello World!"
puts "Hello again"
puts "i like typing this"
puts "this is fun"
puts "yay! printing"
puts "i'd much rather you not"
puts "i said do not touch this"
puts "you cant handle the true"
